#!/bin/bash
set -e

PUID=${PUID:-1000}
PGID=${PGID:-1000}

if [ -n "$TZ" ]; then
    export TZ
fi

if [ ! -f /config/stash_jellyfin_proxy.conf ]; then
    echo "Creating default config file..."
    cat > /config/stash_jellyfin_proxy.conf << 'EOF'
# Stash-Jellyfin Proxy Configuration
# Generated by Docker container

# Stash server settings
STASH_URL = http://localhost:9999
STASH_API_KEY = your_api_key_here

# Proxy server settings
PROXY_BIND = 0.0.0.0
PROXY_PORT = 8096
UI_PORT = 8097

# Authentication (used by Infuse to connect)
SJS_USER = admin
SJS_PASSWORD = password

# Server identification (must be unique, do not change after setup)
SERVER_ID = 

# Library settings
TAG_GROUPS = 
LATEST_GROUPS = Scenes

# Server display name
SERVER_NAME = Stash Media Server

# Connection settings
STASH_TIMEOUT = 30
STASH_RETRIES = 3

# Feature toggles
ENABLE_FILTERS = true
ENABLE_IMAGE_RESIZE = true

# Pagination
DEFAULT_PAGE_SIZE = 100
MAX_PAGE_SIZE = 500

# Image cache
IMAGE_CACHE_MAX_SIZE = 100

# Security
REQUIRE_AUTH_FOR_CONFIG = false

# Logging
LOG_DIR = /config
LOG_FILE = stash_jellyfin_proxy.log
LOG_LEVEL = INFO
LOG_MAX_SIZE_MB = 10
LOG_BACKUP_COUNT = 3
EOF
    echo "Default config created at /config/stash_jellyfin_proxy.conf"
    echo "Please edit this file and set your STASH_API_KEY and SERVER_ID"
fi

chown -R ${PUID}:${PGID} /config
chown -R ${PUID}:${PGID} /app

export CONFIG_FILE=/config/stash_jellyfin_proxy.conf

if [ -n "$SJS_USER" ]; then
    export SJS_USER
fi
if [ -n "$SJS_PASSWORD" ]; then
    export SJS_PASSWORD
fi
if [ -n "$STASH_URL" ]; then
    export STASH_URL
fi
if [ -n "$STASH_API_KEY" ]; then
    export STASH_API_KEY
fi
if [ -n "$PROXY_BIND" ]; then
    export PROXY_BIND
fi
if [ -n "$PROXY_PORT" ]; then
    export PROXY_PORT
fi
if [ -n "$UI_PORT" ]; then
    export UI_PORT
fi
if [ -n "$REQUIRE_AUTH_FOR_CONFIG" ]; then
    export REQUIRE_AUTH_FOR_CONFIG
fi
if [ -n "$LOG_DIR" ]; then
    export LOG_DIR
fi

echo "Starting Stash-Jellyfin Proxy..."
echo "  PUID: ${PUID}"
echo "  PGID: ${PGID}"
echo "  TZ: ${TZ:-UTC}"
echo "  Config: /config/stash_jellyfin_proxy.conf"

exec gosu ${PUID}:${PGID} "$@"
