"""Authentication middleware + IP ban state.

Validates access tokens on non-public endpoints and tracks repeated
failures per IP. Exceeding BAN_THRESHOLD within BAN_WINDOW_MINUTES
flags the IP; banned IPs are silently dropped (no response) to avoid
confirming bans to attackers.

All runtime state (BANNED_IPS, ACCESS_TOKEN, ban thresholds) lives on
stash_jellyfin_proxy.runtime. In-memory _ip_failures is local to this module since
only the auth path touches it.
"""
import logging
import os
import re
import time
from urllib.parse import parse_qs

from stash_jellyfin_proxy import runtime

logger = logging.getLogger("stash-jellyfin-proxy")


# Endpoints that don't require authentication (for client discovery).
# All lowercase for case-insensitive comparison.
PUBLIC_ENDPOINTS = {
    "/",
    "/favicon.ico",
    "/system/info/public",
    "/system/info",
    "/system/ping",
    "/users",
    "/users/public",
    "/users/authenticatebyname",
    "/emby/users/authenticatebyname",
    "/branding/configuration",
    "/branding/splashscreen",
    "/quickconnect/enabled",
    "/quickconnect/initiate",
    "/quickconnect/connect",
    "/userimage",
}

PUBLIC_PREFIXES = [
    "/system/info",
    "/emby/system/info",
    "/videos/",
]


# IP failure tracking: {ip: [(timestamp, path), ...]}
_ip_failures = {}


def get_client_ip(scope) -> str:
    """Extract client IP from request, checking X-Forwarded-For for proxied requests."""
    headers = {}
    for key, value in scope.get("headers", []):
        headers[key.decode().lower()] = value.decode()

    xff = headers.get("x-forwarded-for", "")
    if xff:
        return xff.split(",")[0].strip()

    xri = headers.get("x-real-ip", "")
    if xri:
        return xri.strip()

    client = scope.get("client", ("unknown", 0))
    return client[0] if client else "unknown"


def clear_ip_failures(client_ip: str) -> None:
    """Remove any recorded failure history for an IP. Called after a
    successful auth so a client that finally gets the password right
    doesn't stay one failure away from a ban forever."""
    _ip_failures.pop(client_ip, None)


def record_auth_failure(client_ip: str, path: str, reason: str, user_agent: str = ""):
    """Record a failed auth attempt and check if IP should be banned.

    Rate limits failure counting to 1 per second per IP to avoid instant
    bans from parallel requests (e.g., Infuse fans out 10+ requests on
    startup with stale tokens).
    """
    now = time.time()
    window_seconds = runtime.BAN_WINDOW_MINUTES * 60

    if client_ip in _ip_failures:
        _ip_failures[client_ip] = [
            (ts, p) for ts, p in _ip_failures[client_ip]
            if now - ts < window_seconds
        ]
    else:
        _ip_failures[client_ip] = []

    recent_failures = _ip_failures[client_ip]
    if recent_failures:
        last_failure_time = recent_failures[-1][0]
        if now - last_failure_time < 1.0:
            logger.debug(f"🚫 Auth failed (rate limited): {client_ip} -> {path} ({reason})")
            return

    _ip_failures[client_ip].append((now, path))
    failure_count = len(_ip_failures[client_ip])

    ua_info = f", UA: {user_agent[:50]}" if user_agent else ""
    log_msg = f"🚫 Auth failed: {client_ip} -> {path} ({reason}) [attempt {failure_count}/{runtime.BAN_THRESHOLD}]{ua_info}"
    if failure_count <= 2:
        logger.debug(log_msg)
    else:
        logger.warning(log_msg)

    if failure_count >= runtime.BAN_THRESHOLD:
        runtime.BANNED_IPS.add(client_ip)
        logger.warning(f"🔒 IP BANNED: {client_ip} (exceeded {runtime.BAN_THRESHOLD} failures in {runtime.BAN_WINDOW_MINUTES} minutes)")
        save_banned_ips_to_config()
        del _ip_failures[client_ip]


def save_banned_ips_to_config():
    """Persist the current BANNED_IPS set to the config file."""
    config_file = runtime.CONFIG_FILE
    if not os.path.isfile(config_file):
        return

    banned_str = ", ".join(sorted(runtime.BANNED_IPS)) if runtime.BANNED_IPS else ""

    try:
        with open(config_file, 'r') as f:
            lines = f.readlines()

        found = False
        new_lines = []
        for line in lines:
            stripped = line.strip()
            if stripped.startswith('BANNED_IPS') and '=' in stripped:
                new_lines.append(f'BANNED_IPS = "{banned_str}"\n')
                found = True
            elif stripped.startswith('#') and 'BANNED_IPS' in stripped and '=' in stripped:
                new_lines.append(f'BANNED_IPS = "{banned_str}"\n')
                found = True
            else:
                new_lines.append(line)

        if not found:
            new_lines.append(f'\n# Auto-generated by IP ban system\nBANNED_IPS = "{banned_str}"\n')

        with open(config_file, 'w') as f:
            f.writelines(new_lines)

        logger.info(f"Saved banned IPs to config: {banned_str if banned_str else '(none)'}")
    except Exception as e:
        logger.error(f"Failed to save banned IPs to config: {e}")


class AuthenticationMiddleware:
    """ASGI middleware that validates ACCESS_TOKEN on protected endpoints
    and enforces IP bans."""

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        path = scope.get("path", "")
        client_ip = get_client_ip(scope)

        user_agent = ""
        for key, value in scope.get("headers", []):
            if key.decode().lower() == "user-agent":
                user_agent = value.decode()
                break

        # Silent drop for banned IPs — no response means the connection
        # hangs until the client times out, and attackers don't get
        # confirmation that the IP is banned.
        if client_ip in runtime.BANNED_IPS:
            logger.debug(f"🚫 Silent drop for banned IP: {client_ip} -> {path}")
            return

        # Strip /emby/ prefix for Emby-compatible clients (e.g., SenPlayer)
        path_lower = path.lower()
        if path_lower.startswith("/emby/"):
            stripped_path = path[5:]
            scope = dict(scope)
            scope["path"] = stripped_path
            path = stripped_path
            path_lower = stripped_path.lower()

        is_public = path_lower in PUBLIC_ENDPOINTS
        if not is_public:
            for prefix in PUBLIC_PREFIXES:
                if path_lower.startswith(prefix):
                    is_public = True
                    break
        if not is_public and "/images/" in path_lower:
            is_public = True

        if is_public:
            await self.app(scope, receive, send)
            return

        # Extract token from headers. Scan ALL headers before giving up —
        # clients (Fladder, official Jellyfin web) often send
        # X-Emby-Authorization with only Client/Device/DeviceId (no Token=)
        # alongside X-MediaBrowser-Token or X-Emby-Token in a separate
        # header. Breaking on the first match would reject the request
        # even though a valid token is present.
        token = None
        for key, value in scope.get("headers", []):
            key_lower = key.decode().lower()
            value_str = value.decode()

            if key_lower == "x-emby-token":
                token = value_str
            elif key_lower == "x-mediabrowser-token":
                token = value_str
            elif key_lower == "authorization":
                if value_str.startswith("Bearer "):
                    token = value_str[7:]
                elif "Token=" in value_str:
                    match = re.search(r'Token="([^"]+)"', value_str)
                    if not match:
                        match = re.search(r'Token=([^,\s]+)', value_str)
                    if match:
                        token = match.group(1)
            elif key_lower == "x-emby-authorization":
                match = re.search(r'Token="([^"]+)"', value_str)
                if not match:
                    match = re.search(r'Token=([^,\s]+)', value_str)
                if match:
                    token = match.group(1)

            if token:
                break

        # Check query string for api_key parameter (Jellyfin 10.11+ SDK, some clients)
        if not token:
            query_string = scope.get("query_string", b"").decode()
            if query_string:
                qs = parse_qs(query_string)
                token = (qs.get("api_key") or qs.get("ApiKey") or qs.get("apikey") or [None])[0]

        if token and token == runtime.ACCESS_TOKEN:
            await self.app(scope, receive, send)
            return

        reason = "invalid token" if token else "missing token"
        auth_headers = {
            k.decode().lower(): v.decode()
            for k, v in scope.get("headers", [])
            if k.decode().lower() in ("authorization", "x-emby-authorization", "x-emby-token", "x-mediabrowser-token")
        }
        logger.debug(f"AUTH REJECT: {scope.get('method', '?')} {path} from {client_ip} - {reason} - auth headers: {auth_headers}")
        record_auth_failure(client_ip, path, reason, user_agent)

        response_body = b'{"error": "Unauthorized"}'
        await send({
            "type": "http.response.start",
            "status": 401,
            "headers": [
                [b"content-type", b"application/json"],
                [b"content-length", str(len(response_body)).encode()],
            ],
        })
        await send({
            "type": "http.response.body",
            "body": response_body,
        })
